import javax.swing.JButton;
import javax.swing.JComboBox;

public class Administrador extends javax.swing.JDialog {
    private String peliculaSeleccionada;

    public Administrador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bloquearControlesIniciales();
    }

    public Administrador() {
        super(new javax.swing.JFrame(), true);
        initComponents();
        bloquearControlesIniciales();
    }

    private void bloquearControlesIniciales() {
        JComboSeleccion1.setEnabled(false);
        JComboSeleccion2.setEnabled(false);
        JComboSeleccion3.setEnabled(false);

        JhorarioNap.setEnabled(false);
        JhorarioNap2.setEnabled(false);
        JhorarioNap3.setEnabled(false);

        JhorarioWon1.setEnabled(false);
        JhorarioWon2.setEnabled(false);
        JhorarioWon3.setEnabled(false);

        JhorarioAq1.setEnabled(false);
        JhorarioAq2.setEnabled(false);
        JhorarioAq3.setEnabled(false);

        JSiguientePantalla.setEnabled(false);

        Jpelicula1.setEnabled(false);
        Jpelicula2.setEnabled(false);
        Jpelicula3.setEnabled(false);
    }

    private void desbloquearControlesPeliculas() {
        JComboSeleccion1.setEnabled(true);
        JComboSeleccion2.setEnabled(true);
        JComboSeleccion3.setEnabled(true);

        Jpelicula1.setEnabled(true);
        Jpelicula2.setEnabled(true);
        Jpelicula3.setEnabled(true);
    }

    private void relacionarHorariosConPelicula1() {
        JhorarioNap.setEnabled(true);
        JhorarioNap2.setEnabled(true);
        JhorarioNap3.setEnabled(true);
    }

    private void relacionarHorariosConPelicula2() {
        JhorarioWon1.setEnabled(true);
        JhorarioWon2.setEnabled(true);
        JhorarioWon3.setEnabled(true);
    }

    private void relacionarHorariosConPelicula3() {
        JhorarioAq1.setEnabled(true);
        JhorarioAq2.setEnabled(true);
        JhorarioAq3.setEnabled(true);
    }

    private void bloquearHorariosNoRelacionados() {
        if ("Pelicula 1 (Napoleon)".equals(peliculaSeleccionada)) {
            bloquearHorariosNoRelacionadosConPelicula1();
            bloquearPelicula2y3();
        } else if ("Pelicula 2".equals(peliculaSeleccionada)) {
            bloquearHorariosNoRelacionadosConPelicula2();
            bloquearPelicula1y3();
        } else if ("Pelicula 3".equals(peliculaSeleccionada)) {
            bloquearHorariosNoRelacionadosConPelicula3();
            bloquearPelicula1y2();
        }
    }
private void bloquearHorariosNoRelacionadosConPelicula1() {
    JhorarioNap.setEnabled(true);
    JhorarioNap2.setEnabled(false);
    JhorarioNap3.setEnabled(false);
    JhorarioWon1.setEnabled(false);
    JhorarioWon2.setEnabled(true);
    JhorarioWon3.setEnabled(true);
    JhorarioAq1.setEnabled(false);
    JhorarioAq2.setEnabled(true);
    JhorarioAq3.setEnabled(true);
}

private void bloquearHorariosNoRelacionadosConPelicula2() {
    JhorarioNap.setEnabled(false);
    JhorarioNap2.setEnabled(true);
    JhorarioNap3.setEnabled(true);
    JhorarioWon1.setEnabled(true);
    JhorarioWon2.setEnabled(false);
    JhorarioWon3.setEnabled(true);
    JhorarioAq1.setEnabled(true);
    JhorarioAq2.setEnabled(false);
    JhorarioAq3.setEnabled(true);
}

private void bloquearHorariosNoRelacionadosConPelicula3() {
    JhorarioNap.setEnabled(false);
    JhorarioNap2.setEnabled(true);
    JhorarioNap3.setEnabled(true);
    JhorarioWon1.setEnabled(true);
    JhorarioWon2.setEnabled(true);
    JhorarioWon3.setEnabled(false);
    JhorarioAq1.setEnabled(true);
    JhorarioAq2.setEnabled(true);
    JhorarioAq3.setEnabled(false);
}
private void bloquearPelicula1y3() {
    Jpelicula1.setEnabled(false);
    Jpelicula3.setEnabled(false);
}

private void bloquearPelicula2y3() {
    Jpelicula2.setEnabled(false);
    Jpelicula3.setEnabled(false);
}

private void bloquearPelicula1y2() {
    Jpelicula1.setEnabled(false);
    Jpelicula2.setEnabled(false);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Jhorarios = new javax.swing.JButton();
        Jpelicula = new javax.swing.JButton();
        Jsala = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JhorarioNap = new javax.swing.JButton();
        JhorarioNap2 = new javax.swing.JButton();
        JhorarioNap3 = new javax.swing.JButton();
        JhorarioWon1 = new javax.swing.JButton();
        JhorarioWon2 = new javax.swing.JButton();
        JhorarioWon3 = new javax.swing.JButton();
        JhorarioAq2 = new javax.swing.JButton();
        JhorarioAq3 = new javax.swing.JButton();
        JhorarioAq1 = new javax.swing.JButton();
        JComboSeleccion1 = new javax.swing.JComboBox<>();
        JComboSeleccion2 = new javax.swing.JComboBox<>();
        JComboSeleccion3 = new javax.swing.JComboBox<>();
        JSiguientePantalla = new javax.swing.JButton();
        Jpelicula1 = new javax.swing.JButton();
        Jpelicula2 = new javax.swing.JButton();
        Jpelicula3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        Jhorarios.setBackground(new java.awt.Color(0, 102, 102));
        Jhorarios.setForeground(new java.awt.Color(255, 255, 255));
        Jhorarios.setText("Horarios");

        Jpelicula.setBackground(new java.awt.Color(0, 102, 102));
        Jpelicula.setForeground(new java.awt.Color(255, 255, 255));
        Jpelicula.setText("Pelicula");
        Jpelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JpeliculaActionPerformed(evt);
            }
        });

        Jsala.setBackground(new java.awt.Color(0, 102, 102));
        Jsala.setForeground(new java.awt.Color(255, 255, 255));
        Jsala.setText("Sala");
        Jsala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JsalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jhorarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jpelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jsala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(Jpelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(Jhorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(Jsala, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logocinerd (2).png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        JhorarioNap.setText("15:00");
        JhorarioNap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JhorarioNapActionPerformed(evt);
            }
        });

        JhorarioNap2.setText("18:00");
        JhorarioNap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JhorarioNap2ActionPerformed(evt);
            }
        });

        JhorarioNap3.setText("21:00");
        JhorarioNap3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JhorarioNap3ActionPerformed(evt);
            }
        });

        JhorarioWon1.setText("11:00");
        JhorarioWon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JhorarioWon1ActionPerformed(evt);
            }
        });

        JhorarioWon2.setText("13:00");
        JhorarioWon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JhorarioWon2ActionPerformed(evt);
            }
        });

        JhorarioWon3.setText("19:00");
        JhorarioWon3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JhorarioWon3ActionPerformed(evt);
            }
        });

        JhorarioAq2.setText("17:00");
        JhorarioAq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JhorarioAq2ActionPerformed(evt);
            }
        });

        JhorarioAq3.setText("19:00");
        JhorarioAq3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JhorarioAq3ActionPerformed(evt);
            }
        });

        JhorarioAq1.setText("14:00");
        JhorarioAq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JhorarioAq1ActionPerformed(evt);
            }
        });

        JComboSeleccion1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar sala", "2D", "3D", "3DXD" }));
        JComboSeleccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboSeleccion1ActionPerformed(evt);
            }
        });

        JComboSeleccion2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Sala", "2D", "3D", "3DXD" }));

        JComboSeleccion3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar sala", "2D", "3D", "3DXD" }));

        JSiguientePantalla.setText("Ir a seleccion de asientos");

        Jpelicula1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/napoleon-thai-movie-poster-sm.jpg"))); // NOI18N
        Jpelicula1.setText("Pelicula 1");
        Jpelicula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jpelicula1ActionPerformed(evt);
            }
        });

        Jpelicula2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wonka_99581 (1).jpg"))); // NOI18N
        Jpelicula2.setText("Pelicula 2");
        Jpelicula2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jpelicula2ActionPerformed(evt);
            }
        });

        Jpelicula3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aquaman_y_el_reino_perdido_99744 (1).jpg"))); // NOI18N
        Jpelicula3.setText("Pelicula 3");
        Jpelicula3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jpelicula3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setText("Napoleon");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setText("Genero: Cine Historico");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setText("Año: 2023");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setText("Napoleon");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setText("Wonka");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel7.setText("Genero: Cine Familiar");

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel8.setText("Genero: Superheroes");

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel9.setText("Año: 2023");

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel10.setText("Año: 2023");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Jpelicula2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Jpelicula1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jpelicula3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 62, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JhorarioWon2)
                    .addComponent(JhorarioWon3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(JSiguientePantalla))
                    .addComponent(JhorarioAq3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JhorarioAq1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JhorarioAq2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addComponent(JComboSeleccion3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JhorarioNap2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JhorarioNap3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JhorarioNap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JhorarioWon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JComboSeleccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JComboSeleccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(135, 135, 135)))
                .addGap(121, 121, 121))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JhorarioNap)
                                    .addComponent(JComboSeleccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addComponent(JhorarioNap2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JhorarioNap3))
                            .addComponent(Jpelicula1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Jpelicula2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jpelicula3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JhorarioWon1)
                            .addComponent(JComboSeleccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(JhorarioWon2)))
                .addGap(18, 18, 18)
                .addComponent(JhorarioWon3)
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JhorarioAq1)
                    .addComponent(JComboSeleccion3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JhorarioAq2)
                .addGap(18, 18, 18)
                .addComponent(JhorarioAq3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JSiguientePantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JsalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JsalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JsalaActionPerformed

    private void JpeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JpeliculaActionPerformed
 System.out.println("Evento generado por: " + evt.getSource());

    desbloquearControlesPeliculas();

    peliculaSeleccionada = (String) ((JButton) evt.getSource()).getText();
    
    switch (peliculaSeleccionada) {
        case "Pelicula 1 (Napoleon)":
            relacionarHorariosConPelicula1();
            break;
        case "Pelicula 2":
            relacionarHorariosConPelicula2();
            break;
        case "Pelicula 3":
            relacionarHorariosConPelicula3();
            break;
        default:
            break;
    }

    bloquearHorariosNoRelacionados();



    }//GEN-LAST:event_JpeliculaActionPerformed

    private void JhorarioNapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JhorarioNapActionPerformed
  
    }//GEN-LAST:event_JhorarioNapActionPerformed

    private void JhorarioNap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JhorarioNap2ActionPerformed

    }//GEN-LAST:event_JhorarioNap2ActionPerformed

    private void JhorarioNap3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JhorarioNap3ActionPerformed

    }//GEN-LAST:event_JhorarioNap3ActionPerformed

    private void JhorarioWon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JhorarioWon1ActionPerformed

                 // TODO add your handling code here:
    }//GEN-LAST:event_JhorarioWon1ActionPerformed

    private void JhorarioWon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JhorarioWon2ActionPerformed

    }//GEN-LAST:event_JhorarioWon2ActionPerformed

    private void JhorarioWon3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JhorarioWon3ActionPerformed

    }//GEN-LAST:event_JhorarioWon3ActionPerformed

    private void JhorarioAq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JhorarioAq1ActionPerformed

    }//GEN-LAST:event_JhorarioAq1ActionPerformed

    private void JhorarioAq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JhorarioAq2ActionPerformed

    }//GEN-LAST:event_JhorarioAq2ActionPerformed

    private void JhorarioAq3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JhorarioAq3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JhorarioAq3ActionPerformed

    private void JComboSeleccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboSeleccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboSeleccion1ActionPerformed

    private void Jpelicula3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jpelicula3ActionPerformed
       desbloquearControlesPeliculas();
        peliculaSeleccionada = "Pelicula 3 (Aquaman)";
        relacionarHorariosConPelicula3();
    }//GEN-LAST:event_Jpelicula3ActionPerformed

    private void Jpelicula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jpelicula1ActionPerformed
desbloquearControlesPeliculas();
        peliculaSeleccionada = "Pelicula 1 (Napoleon)";
        relacionarHorariosConPelicula1();
    }//GEN-LAST:event_Jpelicula1ActionPerformed

    private void Jpelicula2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jpelicula2ActionPerformed
        desbloquearControlesPeliculas();
        peliculaSeleccionada = "Pelicula 2 (Wonka)";
        relacionarHorariosConPelicula2();
    }//GEN-LAST:event_Jpelicula2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Administrador dialog = new Administrador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JComboSeleccion1;
    private javax.swing.JComboBox<String> JComboSeleccion2;
    private javax.swing.JComboBox<String> JComboSeleccion3;
    private javax.swing.JButton JSiguientePantalla;
    private javax.swing.JButton JhorarioAq1;
    private javax.swing.JButton JhorarioAq2;
    private javax.swing.JButton JhorarioAq3;
    private javax.swing.JButton JhorarioNap;
    private javax.swing.JButton JhorarioNap2;
    private javax.swing.JButton JhorarioNap3;
    private javax.swing.JButton JhorarioWon1;
    private javax.swing.JButton JhorarioWon2;
    private javax.swing.JButton JhorarioWon3;
    private javax.swing.JButton Jhorarios;
    private javax.swing.JButton Jpelicula;
    private javax.swing.JButton Jpelicula1;
    private javax.swing.JButton Jpelicula2;
    private javax.swing.JButton Jpelicula3;
    private javax.swing.JButton Jsala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
